package com.sachinbendigeri.spark.CWT.constants

object Constants {
  val PARAM_RUN_INSTANCE_TIME: String = "PARAM_RUN_INSTANCE_TIME"
  val PARAM_VEHICLES_TABLE: String = "PARAM_VEHICLES_TABLE"
  val PARAM_ACCIDENTS_TABLE: String = "PARAM_ACCIDENTS_TABLE"
  val PARAM_CASUALTIES_TABLE: String = "PARAM_CASUALTIES_TABLE"
  val PARAM_REFERENCE_DATA_FOLDER : String = "PARAM_REFERENCE_DATA_FOLDER"

  val PARAM_VEHICLES_DATA_FILE: String = "PARAM_VEHICLES_DATA_FILE"
  val PARAM_ACCIDENTS_DATA_FILE: String = "PARAM_ACCIDENTS_DATA_FILE"
  val PARAM_CASUALTIES_DATA_FILE: String = "PARAM_CASUALTIES_DATA_FILE"
  val PARAM_ACCIDENTSVEHICLESCASUALTIES_TABLE: String = "PARAM_ACCIDENTSVEHICLESCASUALTIES_TABLE"
}